package group

var Name = [][]string{
	{`2019-02-23 Barceló Maya Beach, Riviera Maya, Quintana Roo, Mexico`, `2019-02-23 - Barceló Maya Beach Resort, Riviera Maya, Mexico`},
	{`A Different Kind of Human (Step II)`, `A Different Kind of Human`},
	{`Adrenalin Baby - Johnny Marr Live`, `MARR`},
	{`Anjunadeep 10`, `Anjunadeep 10 Sampler: Part 2`},
	{`Apotheosis, Vol. 1: Mozart - The Final Quartets`, `Mozart: The Final Quartets (apotheosis vol. 1)`},
	{`Back and Forth`, `Back & Forth`},
	{`Back to Mine: Nightmares on Wax`, `Back to Mine`},
	{`Beck-Ola`, `Truth/Beck-Ola`},
	{`Bob Stanley & Pete Wiggs Present Three Day Week (When The Lights Went Out 1972 - 1975)`, `Three Day Week: When The Lights Went Out 1972–1975`},
	{`Brazilliance Vol. 1`, `Brazilliance Vol. 2`},
	{`Brazilliance, Volume 2`, `Brazilliance Volume 1`},
	{`Club Edition Summer 2015`, `Edition 2`},
	{`Complete String Quartets, Vol. 1`, `String Quartets`},
	{`Corail (Remixed)`, `Corail`},
	{`DJ-Kicks`, `DJ-Kicks: Laurel Halo`},
	{`Destination Goa - The Eleventh Chapter`, `Destination`},
	{`Dur Dur of Somalia Volume 1 / Volume 2`, `Dur Dur of Somalia - Volume 1, Volume 2`},
	{`ERR REC Library Vol.2 Science & Technology`, `ERR REC Library Vol​.​2 Science & Technology`},
	{`Episode 1`, `Episode 2`},
	{`Eurobeat Festival Vol. 1`, `Eurobeat Festival Vol. 8`},
	{`Even for just the briefest moment  /  Keep charging this "expiation"  /  Plug in to      making it slightly better`, `Even For Just The Briefest Moment / Keep Charging This “expiation” / Plug In To Making It Slightly Better`},
	{`Everything Not Saved Will Be Lost Part 1 (Remixes)`, `Everything Not Saved Will Be Lost Part 1`},
	{`Everything Not Saved Will Be Lost Part 1`, `Everything Not Saved Will Be Lost Part 1 (Remixes)`},
	{`Everything She Wants`, `Everything She Wants (Remix)`},
	{`FRKWYS Vol. 15: Serenitatem`, `FRKWYS 15: Serenitatem`},
	{`Fantast Remixes, Pt. 2`, `Fantast Remixes, Pt. 3`},
	{`Formations Magnétiques et Phénomènes D’incertitude`, `Formations Magnetiques Et Phenomenes D'incertitude`},
	{`Future Hndrxx Presents The WIZRD`, `Future Hndrxx Presents: The WIZRD`},
	{`Galactic Killer Drums Phaze 4`, `Galactic Killer Drums`},
	{`Heinz Music Best Of Vol. 1`, `Heinz Music Best Of, Vol. 1`},
	{`Jack Le Freak (Extended Remix '87)`, `Le Freak`},
	{`Jesus Christ Superstar - A Rock Opera`, `Jesus Christ Superstar`},
	{`John Wick: Chapter 2`, `John Wick: Chapter 2 (Original Motion Picture Soundtrack)`},
	{`Late Night Tales: Floating Points`, `LateNightTales: Floating Points`},
	{`Let Freedom Ring`, `''Let Freedom Ring''`},
	{`Life of Leaf LP`, `Life of Leaf`},
	{`Live At Carnegie Hall 1977`, `Live At Carnegie Hall`},
	{`Mahler's 1st Symphony In D Major "Titan"`, `Symphony No. 1 "The Titan"`},
	{`Mendelssohn: Violin Concerto in D Minor & String Symphonies Nos. 1-6`, `Violin Concerto in D Minor & String Symphonies Nos. 1-6`},
	{`More Moonglow - The Rock Hard EP`, `Moonglow`},
	{`My Laptops 2001 - 2006`, `My Laptops 2001-2006`},
	{`Mystic Warrior`, `Mystic Warrior EP`},
	{`N9NA Collection 2`, `N9NA`},
	{`Nigeria 70 - No Wahala: Highlife, Afro-Funk & Juju 1973-1987`, `Nigeria 70: No Wahala: Highlife, Afro-Funk & Juju 1973-1987`},
	{`Nova Tunes 3.5`, `Nova Tunes 3.9`},
	{`ONDA (온다)`, `ONDA`},
	{`Pink & Blue (RAC Mix)`, `Pink & Blue`},
	{`Prophecy + Progress`, `Prophecy + Progress: UK Electronics 1978-1990`},
	{`Quentin Tarantino's Once Upon a Time in Hollywood Original Motion Picture Soundtrack`, `Once Upon a Time in Hollywood`},
	{`Remember The Night - Live at EPIC Prague, December 2018`, `Remember the Night (Live at Epic Prague, December 2018)`},
	{`Remind Me (The Classic Elektra Recordings 1978-1984)`, `Remind Me: The Classic Elektra Recordings 1978-1984`},
	{`Road Chronicles Live!`, `Road Chronicles: Live!`},
	{`Samiyam - reflectionz`, `reflectionz`},
	{`Silent Piano: Songs for Sleeping 2`, `Silent Piano (Songs for Sleeping) 2`},
	{`Soul Jazz Records presents CONGO REVOLUTION – Revolutionary and Evolutionary Sounds from the Two Congos 1955-62`, `Congo Revolution: Revolutionary and Evolutionary Sounds from the Two Congos (1955-62)`},
	{`Sounds From The Village Vol. 1`, `Sounds from the Village, Vol. 2`},
	{`Souvenir`, `Souvenir Α CΑRΕΕR ΑΝΤΗΟLΟGΥ 1979-2019`},
	{`Strange Pleasure + New Dawn`, `Strange Pleasure`},
	{`Super Onze - Gao`, `Enregistrés Pour Yehia Le Marabout`},
	{`Symphony in G minor / O Garatuja: Prelude / Série brasileira`, `Symphony in G Minor, O Garatuja Prelude & Série brasileira`},
	{`Symphony no. 1 in D major`, `Symphony no. 4 in E-flat major "Romantic"`},
	{`Tchaikovsky: Symphony No. 4 & Mussorgsky: Pictures at an Exhibition`, `Tchaikovsky: Symphony No. 4 / Mussorgsky: Pictures at an Exhibition`},
	{`The Budos Band`, `The Budos Band V`},
	{`The Legend Lives On`, `The Legend`},
	{`The Valentines Massacre - Amen Project, Pt. 2`, `The Valentines Massacre - Amen Project Pt. 2`},
	{`The Vursiflenze Mismantler`, `The  Vursiflenze Mismantler`},
	{`Two Roomed Hotel`, `Two Roomed Motel`},
	{`Voice Of Resistance (صوت المقاومة)`, `Voice Of Resistance`},
	{`Warehouse 10, Volume 8`, `Warehouse 10 Volume 8`},
	{`marasy collection ～marasy original songs best & new～`, `marasy collection ～marasy original songs best & new`},
}
